#!/bin/bash

set -e # halt on first error

latest_deb='pagegen_2.0.4_all.deb'
latest_tar='pagegen-2.0.4.tar.gz'
unpacked_tar_dir='pagegen-2.0.4'

find "$PAGEGEN_TARGET_DIR" -type f -exec sed -i "s#PAGEGEN_LATEST_DEB#$latest_deb#g" {} \;
find "$PAGEGEN_TARGET_DIR" -type f -exec sed -i "s#PAGEGEN_LATEST_TAR#$latest_tar#g" {} \;
find "$PAGEGEN_TARGET_DIR" -type f -exec sed -i "s#UNPACKED_TAR_DIR#$unpacked_tar_dir#g" {} \;
