#!/bin/bash

set -e # Halt on first error
#set -x # Show commands

pg_site="/home/oliver/Personal/projects/pagegen/pg_site"

# Run common hook
. "$pg_site/common_hooks/post_generate"

echo "Todos:"
cat "$pg_site/TODO"
grep -R TODO "$PAGEGEN_SOURCE_DIR"/* | sed 's/^/  * /'
grep -R TODO "/home/oliver/Personal/projects/pagegen/v2/"*.py | sed 's/^/  * /'
grep -R TODO "/home/oliver/Personal/projects/pagegen/v2/pagegen" | sed 's/^/  * /'
echo