#!/bin/bash

# Deplpoyment

set -e

source "$deploy_assets_dir/${PAGEGEN_ENVIRONMENT}_ftp.conf"

chmod_dirs="$(find "$PAGEGEN_TARGET_DIR" -type d | sed "s#^$PAGEGEN_TARGET_DIR#$ftp_target_dir# ; s/^/chmod 755\ /")"
chmod_files="$(find "$PAGEGEN_TARGET_DIR" -type f | sed "s#^$PAGEGEN_TARGET_DIR#$ftp_target_dir# ; s/^/chmod 644\ /")"

# NB! TLS at fastline is broken, so need "set ssl:verify-certificate no" in ~/.lftp/rc
# NB!2 Note that 404.pl tracking page needs moving to cgi-bin and giving appropriate perms
lftp -f /dev/stdin <<EOFFTP
open $ftp_host
user $ftp_user $ftp_pass
lcd $PAGEGEN_TARGET_DIR
mirror --reverse --exclude statistikk --delete $PAGEGEN_TARGET_DIR $ftp_target_dir
$chmod_dirs
$chmod_files
mv $ftp_target_dir/$cgi_404_page_name $ftp_cgi_dir/$cgi_404_page_name
chmod 755 $ftp_cgi_dir/$cgi_404_page_name
bye
EOFFTP