#!/bin/bash

# Check links

set -e

echo -e "Check links [y|n(Default)]?"
read check_links
if [ "$check_links" = "y" ]; then
  link_log="/tmp/linkchecker.csv"
  if [ "$PAGEGEN_ENVIRONMENT" = "stage" ]; then
    pass="-urice -p "
  fi

  linkchecker -ocsv ${pass}$PAGEGEN_BASE_URL | sed '/^#/d ; /^mailto:pagegen@phnd.net/d' > "$link_log"
  if [ "$(wc -l "$link_log")" != "1 $link_log" ]; then
    localc "$link_log"
  fi
fi