#!/bin/bash

# Check links

set -e

echo -e "Check links [y|n(Default)]?"
read check_links
if [ "$check_links" = "y" ]; then
  link_log="/tmp/linkchecker.csv"

  linkchecker -ocsv $PAGEGEN_BASE_URL | sed '/^#/d ; /^mailto:pagegen@phnd.net/d' > "$link_log"
  if [ "$(wc -l "$link_log")" != "1 $link_log" ]; then
    less "$link_log"
  fi
fi
