#!/bin/bash

# Setup page template for environment

set -e

master_page_template="$PAGEGEN_SITE_DIR/templates/master_page.tpl"
page_template="$PAGEGEN_SITE_DIR/templates/page.tpl"
svg_css="$PAGEGEN_SITE_DIR/deploy_assets/font_awesome_svgs/font-awesome-svg-selection.css"
site_css="$PAGEGEN_SITE_DIR/deploy_assets/site.css"
site_javascript="$PAGEGEN_SITE_DIR/deploy_assets/site.js"
pagegen_logo_svg="$PAGEGEN_SITE_DIR/deploy_assets/pagegen.svg"


# Trawl template and replace placeholders as apropriate
{
  while read line; do
    case "$line" in
      "PAGEGEN_ANALYTICS_SCRIPT")
        if [ "$PAGEGEN_ENVIRONMENT" = "prod" ]; then
          echo "<meta name=\"google-site-verification\" content=\"h9pxP5_cbPYfxaHUtlg4XGHgB_WR9G2pmapS8qShDSM\" />
<script type=\"text/javascript\">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-9947760-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>"
        fi
      ;;
      "PAGEGEN_SITE_CSS")
        echo "<style>"
        if [ "$PAGEGEN_ENVIRONMENT" = "prod" ] || [ "$PAGEGEN_ENVIRONMENT" = "stage" ]; then
          python -m rcssmin < "$site_css"
          python -m rcssmin < "$svg_css"
        else
          cat "$site_css"
          cat "$svg_css"
        fi
        echo "</style>"
      ;;
      "PAGEGEN_SITE_JAVASCRIPT")
        echo "<script>"
        if [ "$PAGEGEN_ENVIRONMENT" = "prod" ] || [ "$PAGEGEN_ENVIRONMENT" = "stage" ]; then
          python -m jsmin "$site_javascript"
        else
          cat "$site_javascript"
        fi
        echo "</script>"
      ;;
      "PAGEGEN_LOGO_SVG")
        cat "$pagegen_logo_svg" #| jq -Rr @uri
      ;;
      *)
        echo "$line"
      ;;
    esac
  done < "$master_page_template"
} > "$page_template"

