#!/bin/bash

# Replace variables in generated pages

set -e

latest_version='2.1.1'
latest_deb='pagegen_2.1.1_all.deb'
pg_site="/home/oliver/Personal/projects/pagegen/pg_site"
git_repo="https://github.com/oliverfields/pagegen_v2.git"


find "$PAGEGEN_TARGET_DIR" -type f -exec sed -i "s#PAGEGEN_LATEST_VERSION#$latest_version#g" {} \;
find "$PAGEGEN_TARGET_DIR" -type f -exec sed -i "s#PAGEGEN_LATEST_DEB#$latest_deb#g" {} \;
find "$PAGEGEN_TARGET_DIR" -type f -exec sed -i "s#GIT_REPO#$git_repo#g" {} \;
