#!/bin/bash

# Spell check source files before generation?

set -e

aspell_personal_dictionary="$PAGEGEN_SITE_DIR/build_assets/aspell-pagegen-dictionary.txt"

echo -e "Spell check, remember use 'a' to whitelist words? [y|n(DEFAULT)]?"
read spell_check
if [ "$spell_check" = "y" ]; then
  find "$PAGEGEN_SOURCE_DIR" -type f  -not -executable -not -path "$PAGEGEN_SOURCE_DIR/assets/*" -exec aspell --dont-backup --lang=en --personal=$aspell_personal_dictionary -c {} \;
fi
