#!/bin/bash

# Start test HTTP server

set -e

echo -e "Start test HTTP server? [y|n(DEFAULT)]?"
read spell_check
if [ "$spell_check" = "y" ]; then
  cd "$PAGEGEN_TARGET_DIR" && python -m SimpleHTTPServer
fi