#!/bin/bash

# Start test HTTP server

set -e

#echo -e "Start test HTTP server? [y|n(DEFAULT)]?"
#read test_server 
#if [ "$test_server" = "y" ]; then
  cd "$PAGEGEN_TARGET_DIR" && python3 -m http.server
#fi
