#!/bin/bash

clog_url="https://raw.githubusercontent.com/oliverfields/pagegen_v2/master/CHANGELOG.md"
clog_tmp=$(mktemp)

wget -qO "$clog_tmp" "$clog_url"

echo "Menu exclude: True"
echo "Generate HTML: False"
echo "Link chain exclude: True"
echo ""

sed -r 's/^#\ (.*)/<h1>\1<\/h1>/ ; s/^##\ (.*)/<h2>\1<\/h2>/ ; s/^###\ (.*)/<h3>\1<\/h3>/ ; s/^-\ (.*)/<li>\1<\/li>/' "$clog_tmp" \
| tr '\n' ' ' \
| sed 's/<\/h3>\ \ <li>/<\/h3>\ <ul><li>/g ; s/<\/li>\ \ /<\/li><\/ul>\ /g ; s/<\/li>\ $/<\/li><\/ul>/'

