#!/bin/bash

html="showcase-selection.html"
css="font-awesome-svg-selection.css"

cat << CSSCONTENT1 > "$css"
.fas {
width: 1em;
height: 1em;
display: inline-block;
background-repeat: no-repeat;
background-position: center;
}
CSSCONTENT1

while read -r icon_name hex_colors; do
	IFS=',' read -r -a colors <<< "$hex_colors"
	for color in "${colors[@]}"; do
		cmd="sed \"s%<path\\ %<path\\ fill=\\\"${color}\\\"\\ stroke=\\\"${color}\\\"\\ %g\" \"solid/${icon_name}.svg\" | jq -Rr @uri"
		#echo $cmd
		svg=$(echo "$cmd" | /bin/bash)

		echo ".${icon_name}-${color:1} {"
		echo "background-image: url(\"data:image/svg+xml;utf-8,${svg}\");"
		echo "}"
	done
done < <(sed '/^#/d' include) >> "$css"

cat << HTMLCONTENT1 > "$html"
<html>
<head>
<style>
HTMLCONTENT1

cat "$css" >> "$html"

cat << HTMLCONTENT2 >> "$html"
</style>
</head>
<body>
HTMLCONTENT2

while read -r icon_name hex_colors; do
	IFS=',' read -r -a colors <<< "$hex_colors"
	for color in "${colors[@]}"; do
		echo "<i class=\"fas ${icon_name}-${color:1}\"></i>"
	done
done < <(sed '/^#/d' include) >> "$html"

cat << HTMLCONTENT3 >> "$html"
</body>
</html>
HTMLCONTENT3
