#!/bin/bash

set -e # halt on first error

#echo "$PAGEGEN_HOOK : $PAGEGEN_ENVIRONMENT"

case "$PAGEGEN_ENVIRONMENT" in
  "prod")
    # If interactive shell
    if [ -n "${INTERACTIVE_PAGEGEN_SESSION+1}" ]; then
      . "$PAGEGEN_HOOK_DIR/script/link_check"
    fi
  ;;
esac
