#!/bin/bash

set -e # halt on first error

#echo "$PAGEGEN_HOOK : $PAGEGEN_ENVIRONMENT"

case "$PAGEGEN_ENVIRONMENT" in
  "prod")
    # If interactive shell
    if [ ! -z ${PS1+x} ]; then
      . "$PAGEGEN_HOOK_DIR/script/link_check"
    fi
  ;;
esac
