#!/bin/bash

set -e

if [ "$PAGEGEN_PAGE_HEADER_MENU_EXCLUDE" = "False" ]; then
	rst_source_target_path="${PAGEGEN_PAGE_TARGET_PATH}.txt"
	if [ ! -e "$rst_source_target_path" ]; then
		cp "$PAGEGEN_PAGE_SOURCE_PATH" "$rst_source_target_path"
	fi
fi

