#!/bin/bash

set -e # halt on first error

case "$PAGEGEN_ENVIRONMENT" in
  #"stage"|"prod")
  #;;
  "test")
    echo "Todos:"
    cat "$PAGEGEN_SITE_DIR/TODO"
    grep -R TODO "$PAGEGEN_SOURCE_DIR"/* | sed 's/^/  * /'
    grep -R TODO "/home/oliver/Documents/Projects/pagegen_v2/src/pagegen/"*.py | sed 's/^/  * /'
    echo

  ;;
esac

