#!/bin/bash

set -e # halt on first error

#echo "$PAGEGEN_HOOK : $PAGEGEN_ENVIRONMENT"

case "$PAGEGEN_ENVIRONMENT" in
  "stage"|"prod")
    . "$PAGEGEN_HOOK_DIR/script/cgi_deploy"
    . "$PAGEGEN_HOOK_DIR/script/link_check"
  ;;
esac