#!/bin/bash

set -e # halt on first error

#echo "$PAGEGEN_HOOK : $PAGEGEN_ENVIRONMENT"

target_dir="$PAGEGEN_TARGET_DIR"
svg_css="$PAGEGEN_SITE_DIR/build_assets/font_awesome_svgs/font-awesome-svg-selection.css"
site_sass="$PAGEGEN_SITE_DIR/build_assets/site.sass"
site_css="$PAGEGEN_SITE_DIR/build_assets/site.css"
min_css="$PAGEGEN_SITE_DIR/build_assets/min.css"
site_javascript="$PAGEGEN_SITE_DIR/build_assets/site.js"
min_js="$PAGEGEN_SITE_DIR/build_assets/min.js"


# Compile sass
sassc "$site_sass" "$site_css"

# Minify Font awesome css and concatinate with site.css
python3 -m rcssmin < "$site_css" > "$min_css" 
python3 -m rcssmin < "$svg_css" >> "$min_css" 

# Minify js
python3 -m jsmin "$site_javascript" > "$min_js"

case "$PAGEGEN_ENVIRONMENT" in
  "prod")
    # If interactive shell
    if [ -n "${INTERACTIVE_PAGEGEN_SESSION+1}" ]; then
      . "$PAGEGEN_HOOK_DIR/script/spell_check"
    fi
  ;;
esac
