#!/bin/bash

set -e # Halt on first error
#set -x # Show commands

# Run common hook
. /home/oliver/Personal/projects/pagegen/pg_site/common_hooks/post_generate

# Compress css
yui-compressor -o "$PAGEGEN_SITE_DIR/include/css/site.min.css" "$PAGEGEN_SITE_DIR/include/css/site.css"

# Compress js
site_min_js="$PAGEGEN_TARGET_DIR/include/javascript/site.min.js"
cat "$PAGEGEN_SITE_DIR/include/javascript/jquery.min.js" > "$site_min_js"
yui-compressor "$PAGEGEN_SITE_DIR/include/javascript/pagegen.js" >> "$site_min_js"