<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}} - Pagegen</title>
    <meta name="copyright" content="Copyright &#169; {{year}} Oliver Fields" />
    <meta name="author" content="Oliver Fields">
    <meta name="contact" content="pagegen@phnd.net" />
    <!-- Open graph -->
    <meta property="og:image" content="{{base_url}}/include/images/pagegen_logo_300x300.png"/>
    <meta property="og:site_name" content="Pagegen - Static site generator"/>
    <meta property="og:title" content="{{title}}"/>
    <meta property="og:url" content="{{absolute_url}}"/>
    <meta property="og:description" content="{{description}}"/>
    <!-- /Open graph -->
    <link rel="apple-touch-icon" sizes="72x72" href="{{base_url}}/include/images/pagegen_logo_72x72.png" />
    <link rel="apple-touch-icon" sizes="114x114" href="{{base_url}}/include/images/pagegen_logo_114x114.png" />
    <link rel="apple-touch-icon" sizes="144x144" href="{{base_url}}/include/images/pagegen_logo_144x144.png" />
    <link rel="apple-touch-icon" href="{{base_url}}/include/images/pagegen_logo_57x57.png" />
    <base href="{{base_url}}" />
    <link rel="canonical" href="{{absolute_url}}" />
    <link rel="shortcut icon" href="{{base_url}}/include/images/favicon.ico" type="image/x-icon" />
    <meta name="description" content="{{description}}" />
    <meta name="Generator" content="Pagegen" />
    <link rel="shortcut icon" href="{{base_url}}/include/images/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{{base_url}}/include/css/site.css" type="text/css" />
    <script async defer src="https://buttons.github.io/buttons.js"></script>
PAGEGEN_ANALYTICS_SCRIPT
  </head>
  <body>
    <div id="page" class="clearfix">
      <i class="fas fa-bars" id="hamburger"></i>
      <div id="sidebar">
        <a id="page_logo" href="{{base_url}}"><img src="{{base_url}}/include/images/pagegen_150x28.png" alt="Pagegen" /></a>
        <p id="blurb">Every page is a file<br /><span>Static site generator</span></p>
        <div id="menu">{{menu}}</div>
        <ul id="project-info">
          <li><i class="fas fa-bug"></i> <a href="https://github.com/oliverfields/pagegen_v2_site/issues">Issue tracker</a></li>
          <li><i class="fas fa-envelope"></i> <a href="mailto:pagegen@phnd.net">pagegen@phnd.net</a></li>
        </ul>
        <div class="github-button-container"><a class="github-button" href="https://github.com/oliverfields/pagegen_v2" data-show-count="true" data-size="large" aria-label="Star oliverfields/pagegen_v2 on GitHub">Star</a></div>
      </div><!-- /sidebar -->
      <article id="content">
        {{content}}
        <div class="clearfix prev-next-links">
          <div id="previous_link">{{previous_link}}</div>
          <div id="next_link">{{next_link}}</i></div>
        </div>
        <div id="footer">Copyright &#169; {{year}} Oliver Fields &#8212; Generated by <a href="https://pagegen.phnd.net"><img src="{{base_url}}/include/images/pagegen_54x10.png" /></a></div>
      </article><!-- /content -->
    </div><!-- /page -->
    <script src="{{base_url}}/include/javascript/site.js"></script>
  </body>
</html>
