name: Deploy pagegen.phnd.net
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build_job:
    name: Deploy site
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout website source
        id: checkout-master
        uses: actions/checkout@v2
      - name: Install Pagegen
        run: |
          pip install pagegen
      - name: Generate site
        id: run-pagegen
        run: |
          cd /home/runner/work/pagegen_v2_site/pagegen_v2_site
          pagegen -g "prod"
